services:
  db:
    image: postgres:latest
    container_name: cfupb_postgres
    environment:
      POSTGRES_PASSWORD: "qwerty"
    networks:
      - inner_net
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: xapsiel3301/cfupb
    container_name: cfupb_backend
    environment:
      DB_PASSWORD: "qwerty"
    networks:
      - inner_net
    ports:
      - "8080:8080"
    depends_on:
      - db  # Зависимость от контейнера с базой данных

volumes:
  postgres_data:

networks:
  inner_net:
    driver: bridge
